#!/usr/bin/perl -w 

@npvs = (27,29,30,31,32,33,34,35,36,37,38,39,40,42,43);


foreach $inter(@npvs){
	#print "$inter";
#	$inter=27;
	chdir "/Users/caio/Desktop/S205-PaoloZanoto-27372346/NPV$inter";
	#system("/Applications/research_tools/bowtie2-2.2.9/bowtie2-build -f NPV$inter.fasta NPV$inter");
	
	system("/Applications/research_tools/bowtie2-2.2.9/bowtie2 -x NPV\'$inter\' -S NPV\'$inter\'.sam --no-discordant --no-mixed --threads 20 --fr -1 NPV\'$inter\'_R1_001_val_1.fq -2 NPV\'$inter\'_R2_001_val_2.fq");
	#$result = `/Applications/research_tools/trim_galore_v0.4.0/trim_galore --clip_R1 20 --clip_R2 20 --three_prime_clip_R1 2 --three_prime_clip_R2 2 --paired /Users/caio/Desktop/S205-PaoloZanoto-27372346/NPV$inter/NPV"$inter"_R1_001.fastq /Users/caio/Desktop/S205-PaoloZanoto-27372346/NPV$inter/NPV"$inter"_R2_001.fastq`;
	#chdir "/Users/caio/Desktop/S205-PaoloZanoto-27372346";
}

